# Generated by Django 4.2.7 on 2023-12-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycategory',
            name='task',
        ),
    ]
