# Generated by Django 4.2.7 on 2023-12-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=20)),
                ('task_description', models.TextField(max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
                ('task_assign_date', models.DateTimeField()),
            ],
        ),
    ]
