# Generated by Django 4.2.7 on 2023-12-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_remove_mycategory_task'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='task_category',
            field=models.ManyToManyField(to='categorys.mycategory'),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='task_assign_date',
            field=models.DateField(),
        ),
    ]
